### ISSUE TITLE
uncrustify.create not working (anymore?)

### ISSUE THREAD

**Issue by joergrech** [LaurentTreguier/vscode-uncrustify#10]
Whe I want to generate a default config file using "uncrustify.create" I get the following error from VS Code - after installing it for the first time and restarting CS Code: 

> Command "uncrustify.create" not found.

**Comment by LaurentTreguier** [comment]
Yes, it looks like I forgot to update the package.json file so that every command activates the extension automatically. I'll push an update as soon as I can. In the meantime it should work if you open a file that contains some code in a language that is supported by Uncrustify.
