### ISSUE TITLE
Parse ${workspaceRoot} in configPath

### ISSUE THREAD

**Issue by wangxufire** [LaurentTreguier/vscode-uncrustify#14]
another problem: can't open config file when set configPath in workspace's .vscoe settings.json

**Comment by LaurentTreguier** [comment]
Is parsing `${workspaceRoot}` necessary ? I am thinking that having a relative path for `uncrustify.configPath` should automatically assume that the path is relative to the workspace root

**Comment by wangxufire** [comment]
It doesn't work when I set a relative path. I workd with multiroot workspace.

**Comment by LaurentTreguier** [comment]
Sorry, I expressed myself badly. It doesn't work for now indeed, but I was thinking that I could just change the extension to interpret relative paths as relative to the current workspace.

**Comment by wangxufire** [comment]
Excellent! Thanks.
