### ISSUE TITLE
add support for processing .pde files?

### ISSUE THREAD

**Issue by rubyquaildesign** [LaurentTreguier/vscode-uncrustify#16]
they're basically Java files but vscode gives them a different syntax name.

**Comment by LaurentTreguier** [comment]
With https://marketplace.visualstudio.com/items?itemName=Tobiah.language-pde the language ID is `pde`. Is that the right language ID ?

**Comment by rubyquaildesign** [comment]
I believe so, although in the bar at the bottom of the window, it says the language is `Processing` so it would certainly be one of those two
