### ISSUE TITLE
can't use default .cfg

### ISSUE THREAD

**Issue by jhoogeboom** [LaurentTreguier/vscode-uncrustify#17]
I want to use one config for all my projects, so I've added it my user settings:

"uncrustify.configPath": "/Users/myuser/.vscode/uncrustify.cfg"

using this cfg:
https://gist.github.com/mkroman/1372117#file-uncrustify-cfg

<img width="606" alt="screen shot 2017-11-14 at 10 59 31" src="https://user-images.githubusercontent.com/1828504/32773888-ed43f2ea-c92a-11e7-97e5-d70518820473.png">

these are all the options presented, how to actually format something?

**Comment by LaurentTreguier** [comment]
The actual formatting is an integral part of VSCode; once you've opened a file that  uncrustify can format, just search for the `Format Document` command. As long as the file you opened can be formatted, this command should be available.

**Comment by jhoogeboom** [comment]
Thanks! Just switched from Atom where this was functionality wrapped in beautify, seems to work fine now.
