### ISSUE TITLE
pkg "uncrustify" keeps reinstalling

### ISSUE THREAD

**Issue by decimad** [LaurentTreguier/vscode-uncrustify#21]
Hey,
on my machine the lines 37 ... 74 of "extension.js" keep trying to reinstall "uncrustify" no matter what. I configured  a local copy of uncrustify by Setting a path Manual with "uncrustify.executablePath".

**Comment by LaurentTreguier** [comment]
Indeed, the extension didn't check if a custom path was used before prompting to install uncrustify. It should be fixed in version 2.8.3 which was just pushed to the marketplace
