### ISSUE TITLE
Graphic config editor cannot select

### ISSUE THREAD

**Issue by eternalphane** [LaurentTreguier/vscode-uncrustify#25]
Hi, I just noticed that `select` tags in graphic config editor is replaced by `input` tags after commit e225ffe, as shown in the screenshot below:
![image](https://user-images.githubusercontent.com/11267872/35778889-a40348c2-09ff-11e8-9bf5-a13694e1a16d.png)

Related lines: https://github.com/LaurentTreguier/vscode-uncrustify/blob/e225ffe26d848587bdf894d7aa52fb3cd6ce6341/src/configurator.ts#L10-L16 https://github.com/LaurentTreguier/vscode-uncrustify/blob/e225ffe26d848587bdf894d7aa52fb3cd6ce6341/src/configurator.ts#L199-L203 https://github.com/LaurentTreguier/vscode-uncrustify/blob/e225ffe26d848587bdf894d7aa52fb3cd6ce6341/src/configurator.ts#L215 It seems that L15 makes L200 confuse selectable nodes with simple string nodes. Could you please fix this? Thanks.

**Comment by LaurentTreguier** [comment]
I should check things more carefully when uploading a new version...

**Comment by eternalphane** [comment]
Haha, frequent updates means better.
