### ISSUE TITLE
[Feature request] Pack buttons in dropdown menu

### ISSUE THREAD

**Issue by eternalphane** [LaurentTreguier/vscode-uncrustify#28]
![image](https://user-images.githubusercontent.com/11267872/36373399-004c9742-15a3-11e8-94d4-c724c6a1e664.png)
As shown in the screeshot above, it's annoying that sometimes buttons may hide comments from view. So it maybe better if buttons are placed in a dropdown menu which can collapse when needed.

**Comment by LaurentTreguier** [comment]
I'll look into it
