### ISSUE TITLE
[Feature request] Highlight changed options

### ISSUE THREAD

**Issue by eternalphane** [LaurentTreguier/vscode-uncrustify#29]
Since sometimes people may forget which option they've changed (yep I'm that idiot) or accidentally click on some options, it would be nice if the changed options are highlighted.

**Comment by LaurentTreguier** [comment]
I agree, I also like knowing what are default values and what's been changed for any kind of configuration.

**Comment by LaurentTreguier** [comment]
Thinking about it, did you mean highlighting changes from the default configuration, or changes that haven't been saved to the file yet ?

**Comment by LaurentTreguier** [comment]
I've gone for the second one, since it's not hard to regenerate a default config file or to look up on github what the default config is.
