### ISSUE TITLE
[Feature request] Format on type

### ISSUE THREAD

**Issue by eternalphane** [LaurentTreguier/vscode-uncrustify#30]
Would be better if `editor.formatOnType` could be respected. Maybe by implementing [`OnTypeFormattingEditProvider`](https://code.visualstudio.com/docs/extensionAPI/vscode-api#OnTypeFormattingEditProvider) and `registerOnTypeFormattingEditProvider`? Thanks.

**Comment by LaurentTreguier** [comment]
At first I thought it would be a hassle, but then I remembered that uncrustify has the `--frag` option to partially format code, so it was trivial to add this 👍

**Comment by eternalphane** [comment]
That's great! I'll try it tomorrow morning.
