### ISSUE TITLE
Configurator categories will not expand

### ISSUE THREAD

**Issue by antcodd** [LaurentTreguier/vscode-uncrustify#35]
Configurator categories show up collapsed on my Ubuntu 16.04 machine, and will not expand.

In the webview debug console when clicking the category is the error:

```
Uncaught ReferenceError: toggle is not defined
    at HTMLHeadingElement.onclick (VM102 webview.html:1)
onclick @ VM102 webview.html:1
```

uncrustify.js is not in the list of active-frame sources, only uncrustify.css is.

Perhaps it is a side effect of the changes in the new Webview API https://code.visualstudio.com/docs/extensions/webview?

Using VSCode 1.23.1. Works on a Windows 10 machine running the same.

**Comment by LaurentTreguier** [comment]
I'll take a look at the new API and see what's going on when I get the chance. Hopefully it's not too hard to fix

**Comment by antcodd** [comment]
Thanks! The new version is working for me now.
