### ISSUE TITLE
Extension stops working on restart

### ISSUE THREAD

**Issue by LeeonTM** [LaurentTreguier/vscode-uncrustify#42]
Im using the extension to format apex code.
Ive gotten it to work a couple of times but it seems very inconsistent.

Every time that I did get it to work it stopped working after restarting VS Code.

Ive tried changing the config path and ive tried removing and re adding the executable to my systems path variable but no luck.

The error that I get when I try opening my config file for instance is: Running the contributed command:'uncrustify.open' failed.

**Comment by LeeonTM** [comment]
Seems like whenever I open the output window and select the Uncrustify output the extension starts working. So whenever I restart or reload my VS Code and do this it works.

**Comment by LaurentTreguier** [comment]
What is:
- your OS ?
- your Uncrustify version and install method ?

**Comment by LeeonTM** [comment]
My OS is windows 10 64 bit.

Im currently using extension build (2.13.6) and executable build (0.68.1) 32 bit.
I installed the extension via the extension browser in VS Code.
I installed the executable via [link](https://sourceforge.net/projects/uncrustify/files/).

And im using VS Code 1.31.

**Comment by LaurentTreguier** [comment]
I managed to reproduce the error; I'm going to look into it
EDIT: I seemingly reproduce it so well that even when selecting the Uncrustify output it still doesn't work...

**Comment by LaurentTreguier** [comment]
When I hide the bottom panel, everything seems to work fine. But as soon as the bottom panel is showing, things start to go wrong.

**Comment by LaurentTreguier** [comment]
It should be fixed in v2.13.7 (please do re-open if it's not)
