### ISSUE TITLE
Different config paths for different platforms

### ISSUE THREAD

**Issue by ttnghia** [LaurentTreguier/vscode-uncrustify#46]
Hi,

I have to work on multiple computers (Windows + Mac + Linux). Thus, I have to config path to uncrustify executable differently on different computers. Can you provide a different config path for different platforms, please? For example, currently we have

```
"uncrustify.executablePath": "some_path/uncrustify.exe"
```

It would be better if we have:
```
"uncrustify.WinExecutablePath": "some_path/uncrustify.exe",
"uncrustify.LinuxExecutablePath": "some_path/uncrustify",
"uncrustify.MacExecutablePath": "some_path/uncrustify"
```

Thank you.

**Comment by LaurentTreguier** [comment]
Added in 2.15.1

**Comment by ttnghia** [comment]
Great! Thank you so much.
I forgot to mention about configPath. Can you add more options to the configPath too, please? Such as from
```
"uncrustify.configPath": "some_path/MyUncrustify.cfg"
```

Change to
```
"uncrustify.configPath.windows": "some_path/MyUncrustify.cfg",
"uncrustify.configPath.linux": "some_path/MyUncrustify.cfg",
"uncrustify.configPath.osx": "some_path/MyUncrustify.cfg"
```
