### ISSUE TITLE
Extension unable to load

### ISSUE THREAD

**Issue by kenhuman** [LaurentTreguier/vscode-uncrustify#47]
The latest release causes the extension to fail to load. The error seems to exist in the `contributes.configuration` section of the package manifest. When loading the extension, VS Code attempts to access a variable `uncrustify.executablePath.linux`, but `uncrustify.executablePath` is null. Suggest changing to something like:

```
"uncrustify.executablePath": {
    "type": "object",
    "default": {
        "linux": null,
        "osx": null,
        "windows": null
    },
    "description": "Path to the uncrustify executable",
    "scope": "window"
},
```

**Comment by LaurentTreguier** [comment]
I've removed `uncrustify.executablePath`, since it conflicts with the others.
