### ISSUE TITLE
Prevent Extension from checking for Uncrustify upgrades.

### ISSUE THREAD

**Issue by Arithmeticae** [LaurentTreguier/vscode-uncrustify#48]
My company specifies the version of Uncrustify to use on our projects. This version is not current with the latest uncrustify release. As a consequence of this, every time I open vscode, I get the "Uncrustify can be upgraded" alert.

It would be nice if this was a check that could be turned off, or that remembers that it has already warned you.

**Comment by LaurentTreguier** [comment]
You can now mute the notifications by setting `uncrustify.noUpdates` to `true` in version 2.17.0
