### ISSUE TITLE
No uncrustify.cfg file

### ISSUE THREAD

**Issue by fricco** [LaurentTreguier/vscode-uncrustify#5]
Hello, I'm using Linux Mint and can't find uncrustify.cfg anywhere, although uncrustify is installed. Shouldn't this extension include it? If not, where I can get it?

**Comment by LaurentTreguier** [comment]
How did you install uncrustify ? If you installed it through `apt` or `apt-get`, then `dpkg-query -L uncrustify | grep cfg` should list installed config files.

**Comment by fricco** [comment]
I didn't installed it. so rather was already installed by Mint or by this extension. Nevertheless, I found that the file is actually called defaults.cfg under /usr/share/uncrustify and after updating the extengion config path it worked :)
