### ISSUE TITLE
README.md refers to stale uncrustify.executablePath and uncrustify.configPath options

### ISSUE THREAD

**Issue by 0xabu** [LaurentTreguier/vscode-uncrustify#50]
README.md (which vscode displays in the extension details pane), says:

> uncrustify.executablePath (string): Path to the uncrustify executable if it's not already in the PATH environment variable.
> uncrustify.configPath (string): Path to the uncrustify configuration file.

Those were renamed by #46. This confused me for a while.

**Comment by LaurentTreguier** [comment]
Sorry about that, I should look at my README's more often with this kind of thing.
