### ISSUE TITLE
Support for Objective-C++ (*.mm files)

### ISSUE THREAD

**Issue by jhasse** [LaurentTreguier/vscode-uncrustify#52]
`uncrusitfy` also works with Objective-C++ (.mm file extension), but I can't select the formatter in VS Code with those files (.m works fine).

**Comment by LaurentTreguier** [comment]
Objective-C++ isn't mentioned specifically as officially supported (and Objective-C itself is apparently not the best supported language). I modified the extension however, and you should be able to use the `uncrustify.langOverrides` extension setting: adding a `"objective-cpp": "OC"` entry to this object should enable Objective-C++ formatting as Objective-C.

**Comment by jhasse** [comment]
Works, thanks :)
