### ISSUE TITLE
Does this extension work with mac Visual Studio Code?

### ISSUE THREAD

**Issue by samishchandra** [LaurentTreguier/vscode-uncrustify#54]
I freshly downloaded latest Visual Studio from [here](https://code.visualstudio.com/docs/?dv=osx).

I installed Uncrustify and the extension as per the instructions. I configured it via settings.. 
I am not able to see any formatters registered for any of the `C`, `C++`, `ObjC`, `ObjC++` files.

Here is what I added in the vstudio settings file.
```
    "uncrustify.configPath.osx": "/Users/<username>/.uncrustify.cfg",
    "uncrustify.graphicalConfig": true,
    "uncrustify.executablePath.osx": "/usr/local/bin/uncrustify",
    "uncrustify.langOverrides":{
        "apex": "JAVA",
        "apex-anon": "JAVA",
        "objective-cpp": "OC+",
    },
```

Here is the log I see in the debug console.
```
Debug: extension started
Debug: registered formatter
Debug: uncrustify installed: true
Debug: should uncrustify be installed: undefined
Debug: installers found: none
Debug: installer choice: undefined
```

**Comment by LaurentTreguier** [comment]
No, this extension is only compatible with Visual Studio Code. Visual Studio for Windows and Visual Studio for Mac are completely different editors under the hood, and they have different extension systems

**Comment by samishchandra** [comment]
Thanks for the reply.

Oh okay. Is there an extension that is available to format the vscode currently?

**Comment by samishchandra** [comment]
@LaurentTreguier, sorry i mistyped the issue header, I am currently using vscode for mac only ?

**Comment by LaurentTreguier** [comment]
Yes, I see; your configuration seems perfectly fine, I don't know what the problem is yet. I will test it on mac and see if it works

**Comment by LaurentTreguier** [comment]
I have some questions to try to understand why this happens:
- What does VSCode say when trying to format ? Is it a notification saying something like `No formatter registered for filetype 'cpp'` ?
- How did you install uncrustify ? Does it properly work in the terminal ?
- Have you tried removing and re-intalling the extension ? It is vary rare, but sometimes VSCode does not correctly install extensions (it has happened to someone else with another extension)

**Comment by samishchandra** [comment]
Please find the below screenshots for formatter and vscode settings.

### Formatter commands
![image](https://user-images.githubusercontent.com/2313133/67713407-00be1500-f983-11e9-84b3-309ad06bcd30.png)

For a fresh install and when i disable cpp. I get `No formatter registered for filetype 'objective-cpp'` notification.

### Settings
![image](https://user-images.githubusercontent.com/2313133/67713452-116e8b00-f983-11e9-9ada-1b897f22b258.png)

### How did you install uncrustify ? Does it properly work in the terminal ?
Yes. Installed it via Homebrew. `brew install uncrustify --HEAD`
```
 ~  uncrustify --version
Uncrustify-91076aa
```

### Have you tried removing and re-intalling the extension ?
Done this multiple times.

**Comment by samishchandra** [comment]
Adding following to settings file, made it to work ✅. Thank you.
```
"editor.defaultFormatter": "LaurentTreguier.uncrustify",
```

**Comment by LaurentTreguier** [comment]
Strange, I think it should not need this. But if it works, then great ! 👍
