### ISSUE TITLE
[Feature Request] Support parsing scoped variable for multi-root workspace

### ISSUE THREAD

**Issue by eternalphane** [LaurentTreguier/vscode-uncrustify#56]
One use case is using a universal config file across multiple folders, where `${workspaceFolder:xxx}` is necessary.

**Comment by LaurentTreguier** [comment]
I'm not sure I understand what `${workspaceFolder:xxx}` is supposed to be. Is this like a path that's always relative to the current workspace folder ?

**Comment by eternalphane** [comment]
It's the root of the workspace named `xxx`. Reference: [Variables scoped per workspace folder](https://code.visualstudio.com/docs/editor/variables-reference#_variables-scoped-per-workspace-folder).

**Comment by LaurentTreguier** [comment]
Thanks for the link; it made things clearer. With version 2.18.0 it should now be possible to use `${workspaceFolder:xxx} in multi-root workspaces to reference a single config file across different folders
