### ISSUE TITLE
Apex is not officially supported by Uncrustify

### ISSUE THREAD

**Issue by mihaipopescu** [LaurentTreguier/vscode-uncrustify#6]
Atom-Beautify decided that but Apex it's not officially supported by Uncrustify.
see also this comment: https://github.com/uncrustify/uncrustify/issues/826#issuecomment-263688276

Great job with putting up this extension.

**Comment by LaurentTreguier** [comment]
Looking back at #1, @w0ndersp00n said that Apex looks like Java... So maybe when apex are formatted we should tell uncrustify that it's Java instead ? I'll also mention this in the README
