### ISSUE TITLE
Consider actual filename for formatting the file.

### ISSUE THREAD

**Issue by samishchandra** [LaurentTreguier/vscode-uncrustify#60]
I am using this extension for a while and it's working great.

I am trying to add an option to Uncrustify to better sort import orders using [PR 2710](https://github.com/uncrustify/uncrustify/pull/2710).

However the extension doesn't take `filename` into consideration when formatting. If the extension is using temporary file for formatting can it use the same name as that of the actual filename, so that the above functionality works fine. Thankyou

**Comment by samishchandra** [comment]
Used the following config as workaround.
```
"uncrustify.useReplaceOption": true,
```

**Comment by LaurentTreguier** [comment]
This extension sends the file content through `stdin` to uncrustify, that's why it doesn't sue the file name by default.
And indeed, using `"uncrustify.useReplaceOption": true` fixes it by forcing VSCode to save the file, ans then formatting the file directly.

**Comment by samishchandra** [comment]
But setting this option doesn't work with option "formatOnSave" in VScode. ?

**Comment by LaurentTreguier** [comment]
Setting `useReplaceOption` to `true` and `formatOnSave` to `true` still works for me

**Comment by samishchandra** [comment]
It shows me this process dialog and never completes.
<img width="451" alt="Screen Shot 2020-04-03 at 11 39 24 AM" src="https://user-images.githubusercontent.com/2313133/78394081-d3177080-759f-11ea-977c-ef62bc8a6823.png">

But when I make `useReplaceOption  = false`.. it works.. but doesn't take filename into account though.

**Comment by LaurentTreguier** [comment]
Does it also do this on files outside of Dropbox ?

**Comment by LaurentTreguier** [comment]
Nevermind, Dropbox syncs files on disk, it's not a remote filesystem.

**Comment by LaurentTreguier** [comment]
What are the contents of the test file ?

**Comment by samishchandra** [comment]
May be related issues ?
> https://github.com/microsoft/vscode/issues/50123
> https://github.com/microsoft/vscode/issues/50351
> https://github.com/microsoft/vscode/issues/88149

**Comment by samishchandra** [comment]
If it helps with debugging.. clicking the "Cancel" button above actually outputs the extensions log and formats the file.. which is weird..

**Comment by LaurentTreguier** [comment]
I think the problem comes from the fact that when formatting, it will try to save the file, then saving will cause formatting, which will cause saving, etc.
During formatting, without using `useReplaceOption`, I have to use the file content from VSCode without reading the file on the disk, and I send it to Uncrustify on stdin. There is no way to specify the filename to Uncrustify when sending data through stdin, as far as I know.

**Comment by samishchandra** [comment]
Oh interesting, is there a way to write contents of the file to temporary file with same filename.. and get results of the formatter ? Probably that way we avoid the loop.

**Comment by LaurentTreguier** [comment]
This could be possible, although not very good for performance

**Comment by samishchandra** [comment]
Can we support it with a option to control may be. Thanks.

**Comment by LaurentTreguier** [comment]
This should be possible using `uncrustify.useTempFile` now. Additionally, maybe it will also work with `uncrustify.useReplaceOption`, there was indeed a bug with it that should be fixed now

**Comment by samishchandra** [comment]
Thanks a lot Laurent for fixing the issue in quick time. Really appreciate it.

**Comment by samishchandra** [comment]
Is this available on the latest? or do I have to do something ?

**Comment by LaurentTreguier** [comment]
It should be available on the latest version

**Comment by samishchandra** [comment]
Oh, I think the version it is compatible is `^1.43.0`.. but i am currently on vscode `1.42.0`.. is it a hard restriction or can we lower that version ?

**Comment by samishchandra** [comment]
Btw.. i tested the flag by downloading latest vscode.. and its working as expected. It would be great, if you can lower the version check if possible. Thank you once again to make this possible.
