### ISSUE TITLE
"Upgrade Config File" command dangerously overwrites global default file

### ISSUE THREAD

**Issue by dsifford** [LaurentTreguier/vscode-uncrustify#7]
Hi there,

This might be the intended function of the `Upgrade Config File` command, but that's not explicitly stated (or if it is, it's not immediately evident). Earlier today I executed that command because I wanted to quickly tweak a setting in my global file and I was rudely awoken by my config file being completely reset, which was a soul-shattering mistake on my end. 😢 

Anyway, consider this issue a drop in the suggestion bin that this function should be changed or, at the very least, a confirm warning should be displayed before this happens.

Thanks so much in advance! 😄

**Comment by LaurentTreguier** [comment]
This is clearly a bug... Upgrading the file is supposed to read the config, download the new file, and write the config you had on top of it. The file should not be reset by this.

Did you use the default name for the config file (`uncrustify.cfg`)?
What version of uncrustify are you using? 

But I fear I realized what might cause this : did you use a custom file you already had prior to using this extension?

**Comment by dsifford** [comment]
Thanks for the quick reply @LaurentTreguier 😄 

My global config file (and the one that your extension points to) is located at `~/.dotfiles/uncrustify.cfg`, but it is also symlinked to the canonical `~/.uncrustify.cfg` location for automatic CLI usage.

> What version of uncrustify are you using?

`Uncrustify-0.65_f`

> But I fear I realized what might cause this : did you use a custom file you already had prior to using this extension?

Correct.

Let me know if I can clarify anything else. Thanks again!

**Comment by LaurentTreguier** [comment]
@dsifford Actually, it's something really dumb. You mentioned you used the `Upgrade Config File` command, which is not supposed to be used manually. I'll put safeguards on all commands to prevent weird things like this one from happening.

**Comment by dsifford** [comment]
Haha, well that makes sense. I have a habit of doing dumb things! 😝 

Is there a way to open up the global file for editing using the extension? If not, can that maybe be added in? 

Thanks!

**Comment by LaurentTreguier** [comment]
> Is there a way to open up the global file for editing using the extension ?

What do you mean by 'global file for editing' ?

**Comment by dsifford** [comment]
The `~/.uncrustify.cfg` file. Not a project-level file.

**Comment by LaurentTreguier** [comment]
With [this commit](https://github.com/LaurentTreguier/vscode-uncrustify/commit/bf1c8654dda33de90ddabe339657b5a2e18c220e) I added a command to open the currenlty used config file. So `~/.uncrustify.cfg` can be set in the extension config and can be opened from any project directory afterwards

**Comment by LaurentTreguier** [comment]
Or did you want to be able to open it even when having a project specific config file ?

**Comment by dsifford** [comment]
@LaurentTreguier Nope, you totally nailed it. Thanks so much! 🎉
