### ISSUE TITLE
Can't set indent_columns = output_tab_size in graphical editor

### ISSUE THREAD

**Issue by deepseer** [LaurentTreguier/vscode-uncrustify#8]
And indent_switch_case = indent_columns

There may be more like this. They should be text boxes that support other characters beside digits, not a numeric updown.
Another workaround is to create a checkbox (for output_tab_size, etc.) that overrides a numeric updown.

uncrustify 0.64_d
vscode-uncrustify 2.3.0
vscode 1.12.2
"uncrustify.executablePath": "/usr/local/bin/uncrustify",
"uncrustify.configPath": "/home/MYNAME/uncrustify/mycppcfg.cfg",

**Comment by LaurentTreguier** [comment]
I had no idea that it was possible to set values this way... I'll add some way to override any value with a text box, probably with a checkbox like you suggest.

**Comment by LaurentTreguier** [comment]
The checkbox seems to involve a bit more work, so for now there are simply text boxes for custom values. You can override any value, and your input will be written as is in the config file.
