### ISSUE TITLE
Unable to open configuration file

### ISSUE THREAD

**Issue by IndigoTea** [LaurentTreguier/vscode-uncrustify#9]
I've just installed the Uncrustify extension in VS Code on a Win10 machine, but I'm getting this error when attempting to open the .cfg file:

Unable to open 'Uncrustify configuration': Cannot read property 'tag' of undefined.

When opening the cfg file in Notepad, I see that it's empty. Is there a default config file I can use?

Edit: Closed VS Code, Re-opened, re-ran "Create config file", open config file, and now it works as anticipated.

**Comment by everLEEst** [comment]
No actually It just create Empty file.
when I try to use deafult.cfg(http://uncrustify.sourceforge.net/default.cfg) it works well.
